
title: PricePoint API Reference
description: The documentation for the PricePoint API
theme: just-the-docs

baseurl: /public-api-docs
url: https://price-point.github.io

color_scheme: pricepoint
logo: https://cdn.pricepointmoves.com/public/PricePoint-logo-black_transparent.png
back_to_top: true
back_to_top_text: "Back to top"
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: "Note:"
    color: purple
  notes:
    title: "Notes:"
    color: purple
  warning:
    title: Warning
    color: red